// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7smSZufY_g6ZHibIrVFykbw85yNBCmE',
    appId: '1:659501190693:web:778733bd2e6585dcaf79cc',
    messagingSenderId: '659501190693',
    projectId: 'rentalapp001-6da48',
    authDomain: 'rentalapp001-6da48.firebaseapp.com',
    storageBucket: 'rentalapp001-6da48.firebasestorage.app',
    measurementId: 'G-K2CBGG0S9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa2IFufPwzygIEFuRhK2cNExAFno-zXRs',
    appId: '1:659501190693:android:a612fed7bdadee1aaf79cc',
    messagingSenderId: '659501190693',
    projectId: 'rentalapp001-6da48',
    storageBucket: 'rentalapp001-6da48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvzfzQwd7jghtlm5hCO4rYPjwWz2f1TSA',
    appId: '1:659501190693:ios:86d510e6155722e3af79cc',
    messagingSenderId: '659501190693',
    projectId: 'rentalapp001-6da48',
    storageBucket: 'rentalapp001-6da48.firebasestorage.app',
    iosBundleId: 'com.example.rentalWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvzfzQwd7jghtlm5hCO4rYPjwWz2f1TSA',
    appId: '1:659501190693:ios:86d510e6155722e3af79cc',
    messagingSenderId: '659501190693',
    projectId: 'rentalapp001-6da48',
    storageBucket: 'rentalapp001-6da48.firebasestorage.app',
    iosBundleId: 'com.example.rentalWebapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ7smSZufY_g6ZHibIrVFykbw85yNBCmE',
    appId: '1:659501190693:web:b5505b43f450d74baf79cc',
    messagingSenderId: '659501190693',
    projectId: 'rentalapp001-6da48',
    authDomain: 'rentalapp001-6da48.firebaseapp.com',
    storageBucket: 'rentalapp001-6da48.firebasestorage.app',
    measurementId: 'G-WRDMW73G5T',
  );
}
